export const COMPANY = {
  name: "SEBA Construction & Drilling Ltd",
  shortName: "SEBA",
  tagline: "Building Tanzania's Future",
  established: 2008,
  address: "8th Floor, 1016 Jamhuri Building, Dar es Salaam, Tanzania",
  poBox: "P.O. Box 25487, Dar es Salaam",
  phone1: "+255 753 666 668",
  phone2: "+255 764 106 668",
  phone3: "+255 712 666 666",
  email: "info@sebadrilling.co.tz",
  email2: "sebadrilling@gmail.com",
  website: "www.sebadrilling.co.tz",
  whatsapp: "+255753666668",
  mapUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3962.106045519507!2d39.2819981!3d-6.8197261!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x185c4b03f0e56257%3A0x7333bbc4c67db120!2s1016%20Jamhuri!5e0!3m2!1sen!2stz!4v1714212000000!5m2!1sen!2stz",
  director: "Mr. Khalid A. Salum",
};

export const NAV_LINKS = [
  { href: "/", label: "Home" },
  { href: "/about", label: "About" },
  { href: "/services", label: "Services" },
  { href: "/projects", label: "Projects" },
  { href: "/gallery", label: "Gallery" },
  { href: "/blog", label: "Blog" },
  { href: "/contact", label: "Contact" },
];

export const SERVICES = [
  {
    title: "Borehole Drilling",
    description: "Expert DTH (Down-The-Hole) drilling technology with depths up to 350m. Geological sampling at 1m intervals with yield estimation.",
    icon: "Drill",
    image: "/images/Drilling Works.png",
    details: [
      "DTH Technology with high compressed air",
      "Variable hole sizes per client requirements",
      "Geological rock samples at 1m intervals",
      "Aquifer strike and water rest level recording",
      "Yield estimation for individual aquifers",
    ],
  },
  {
    title: "Groundwater Exploration",
    description: "Comprehensive hydrogeological surveys using ABEM Terrameter SAS 1000 and PQWT S-300 ERT technology.",
    icon: "Search",
    image: "/images/Ground Water Exploration.jpg",
    details: [
      "Electrical Resistivity Tomography (ERT)",
      "Identification of shallow and deep aquifers",
      "Site assessment by qualified geologists",
      "Detailed technical reports",
      "Optimal drilling point recommendations",
    ],
  },
  {
    title: "Civil & Building Construction",
    description: "Full-spectrum construction services including water supply projects, irrigation schemes, buildings, roads, and dams.",
    icon: "Building2",
    image: "/images/Building Construction.jpg",
    details: [
      "Water supply treatment plants and pipelines",
      "Irrigation scheme construction",
      "Building and road construction",
      "Dam construction",
      "Underground and raised water tanks",
    ],
  },
  {
    title: "Dewatering Services",
    description: "Specialized dewatering for mining and construction sites including well point systems, deep wells, and sump pumping.",
    icon: "Droplets",
    image: "/images/Groundwater.jpg",
    details: [
      "Well point systems for sandy soil",
      "Deep well dewatering around mine pits",
      "Sump pumping for temporary works",
      "Submersible pumps up to 100,000 L/hr",
      "Experienced at Bulyanhulu Gold Mine",
    ],
  },
  {
    title: "Diamond & RC Drilling",
    description: "Precision exploration drilling with RC rigs up to 450m and diamond drilling up to 800m depth for mining operations.",
    icon: "Gem",
    image: "/images/Drilling work 2.jpg",
    details: [
      "Reverse Circulation (RC) drilling to 450m",
      "Diamond drilling to 800m depth",
      "Blast hole drilling to 40m",
      "RAB drilling and probe drilling",
      "In-pit RC grade control drilling",
    ],
  },
  {
    title: "Irrigation & Water Supply",
    description: "Complete water infrastructure solutions from feasibility studies to construction of distribution systems.",
    icon: "Waves",
    image: "/images/Irrigation.jpg",
    details: [
      "Gravity water supply schemes",
      "Piped water supply construction",
      "Pump installation and servicing",
      "Water treatment solutions",
      "Distribution point construction",
    ],
  },
];

export const ALL_PROJECTS = [
  {
    name: "Noravia Gold (Tanzania) Ltd",
    client: "Njombe District Council",
    year: "2025",
    category: "Drilling",
    description: "Gold exploration drilling project serving the Njombe region with precision borehole drilling and sample collection.",
    status: "Completed",
    image: "",
  },
  {
    name: "Sotta Mine Cooperation",
    client: "Nyanzaga Sengerema Mwanza",
    year: "2017",
    category: "Drilling",
    description: "Mining cooperation project delivering specialized drilling services in the Mwanza region.",
    status: "Completed",
    image: "",
  },
  {
    name: "Construction of Piped Water Supply at Sitalike Village",
    client: "RUWASA, Katavi",
    year: "2018",
    category: "Water Supply",
    description: "Complete piped water supply system construction for Sitalike Village in Simbo District Council, Katavi.",
    status: "Completed",
    image: "",
  },
  {
    name: "Construction of Piped Water System for Ihenje Village",
    client: "Gairo District Council",
    year: "2016",
    category: "Water Supply",
    description: "Piped water system and civil works for Ihenje Village under contract LGA/143/2016/2017/W/12.",
    status: "Completed",
    image: "",
  },
  {
    name: "Construction of Gravity Water Supply Scheme at Isindagosi Village",
    client: "RUWASA Njombe",
    year: "2017",
    category: "Water Supply",
    description: "Gravity-fed water supply scheme construction bringing clean water to Isindagosi Village in Njombe.",
    status: "Completed",
    image: "",
  },
  {
    name: "Construction of Piped Water Supply for Katsunga Village",
    client: "RUWASA Mpanda",
    year: "2019",
    category: "Water Supply",
    description: "Piped water supply construction for Katsunga Village in Nsimbo District Council.",
    status: "Completed",
    image: "",
  },
  {
    name: "Extension of Chemchem Water Supply to Chekeleni Village",
    client: "RUWASA Mtwara",
    year: "2022-2023",
    category: "Water Supply",
    description: "Extension of Chemchem Water Supply Scheme to Chekeleni Village in Mtwara District, Mtwara Region.",
    status: "Completed",
    image: "/images/Chekeleni Village Mtwara Project.jpeg",
  },
  {
    name: "Feasibility Study & Drilling 18 Productive Boreholes",
    client: "RUWASA Kilosa",
    year: "2023-2024",
    category: "Drilling",
    description: "Comprehensive feasibility study, detailed design, and drilling of 18 productive boreholes for water supply.",
    status: "Completed",
    image: "",
  },
  {
    name: "Construction of Chitoholi Water Supply Scheme",
    client: "RUWASA Tandahimba District",
    year: "2024",
    category: "Water Supply",
    description: "Complete water supply scheme construction for Chitoholi serving the Tandahimba District community.",
    status: "Completed",
    image: "",
  },
  {
    name: "Rehabilitation of Dihimba Water Supply Project",
    client: "RUWASA Mtwara District",
    year: "2023",
    category: "Water Supply",
    description: "Rehabilitation and upgrade of the Dihimba Water Supply Project in Mtwara District.",
    status: "Completed",
    image: "",
  },
  {
    name: "1200 Cubic Metres Water Tank Construction",
    client: "Wang'ombe Njombe - Iringa Region",
    year: "2024",
    category: "Construction",
    description: "Massive 1200 cubic metres water tank construction at Wang'ombe Njombe in Iringa Region.",
    status: "Completed",
    image: "/images/Isindagosi Project Wanging'ombe Njombe.jpeg",
  },
  {
    name: "Water Pumping House Station Construction",
    client: "Wang'ombe Njombe - Iringa Region",
    year: "2024",
    category: "Construction",
    description: "Water pumping house station construction at Wang'ombe Njombe, Iringa Region.",
    status: "Completed",
    image: "",
  },
  {
    name: "Water Tank Tower Construction",
    client: "Mpanda - Katavi Region",
    year: "2024",
    category: "Construction",
    description: "Elevated water tank tower construction in Mpanda, Katavi Region for improved water distribution.",
    status: "Completed",
    image: "",
  },
  {
    name: "Malatu Water Supply Scheme",
    client: "Mtwara Region",
    year: "2024",
    category: "Water Supply",
    description: "Water supply scheme construction for Malatu community in Mtwara Region.",
    status: "Completed",
    image: "",
  },
  {
    name: "Box Culvert Construction",
    client: "Various",
    year: "2024",
    category: "Construction",
    description: "Box culvert construction projects for drainage and road infrastructure.",
    status: "Completed",
    image: "",
  },
  {
    name: "Rigid Pavement Construction",
    client: "Various",
    year: "2024",
    category: "Construction",
    description: "Rigid pavement construction for road projects requiring durable concrete surfaces.",
    status: "Completed",
    image: "",
  },
  {
    name: "Drilling at Stamigold Biharamulo",
    client: "Stamigold",
    year: "2023",
    category: "Drilling",
    description: "Monitoring borehole drilling at Stamigold Biharamulo mining site.",
    status: "Completed",
    image: "",
  },
  {
    name: "Drilling at RUWASA Misenyi Water Project",
    client: "RUWASA Misenyi",
    year: "2022",
    category: "Drilling",
    description: "Borehole drilling and development for RUWASA Misenyi water project.",
    status: "Completed",
    image: "",
  },
  {
    name: "Dewatering at Bulyanhulu Gold Mine",
    client: "Bulyanhulu Gold Mine",
    year: "2021",
    category: "Dewatering",
    description: "Dewatering and depression borehole drilling at Bulyanhulu Gold Mine, Upper West Box Cut Project.",
    status: "Completed",
    image: "",
  },
];

export const PROJECTS = [
  { name: "Noravia Gold (Tanzania) Ltd", client: "Njombe District Council", year: "2025" },
  { name: "Sotta Mine Cooperation", client: "Nyanzaga Sengerema Mwanza", year: "2017" },
  { name: "Construction of Piped Water Supply at Sitalike Village", client: "RUWASA, Katavi", year: "2018" },
  { name: "Construction of Piped Water System for Ihenje Village", client: "Gairo District Council", year: "2016" },
  { name: "Construction of Gravity Water Supply Scheme at Isindagosi Village", client: "RUWASA Njombe", year: "2017" },
  { name: "Construction of Piped Water Supply for Katsunga Village", client: "RUWASA Mpanda", year: "2019" },
  { name: "Extension of Chemchem Water Supply to Chekeleni Village", client: "RUWASA Mtwara", year: "2022-2023" },
  { name: "Feasibility Study & Drilling 18 Boreholes", client: "RUWASA Kilosa", year: "2023-2024" },
  { name: "Construction of Chitoholi Water Supply Scheme", client: "RUWASA Tandahimba", year: "2024" },
  { name: "Rehabilitation of Dihimba Water Supply Project", client: "RUWASA Mtwara", year: "2023" },
  { name: "1200 Cubic Metres Water Tank Construction", client: "Wang'ombe Njombe", year: "2024" },
  { name: "Water Tank Tower Construction", client: "Mpanda Katavi", year: "2024" },
];

export const EQUIPMENT = [
  { name: "Drilling Rig (DTH)", spec: "350m max depth — DTH (Down-The-Hole) Method", category: "Drilling" },
  { name: "RC Drilling Rig", spec: "450m max — Multipurpose RC & Diamond drilling", category: "Drilling" },
  { name: "RC Drilling Rig (200m)", spec: "200m max — Multipurpose RC & Diamond drilling", category: "Drilling" },
  { name: "Diamond Drilling Rig (DD)", spec: "800m max depth — Precision core sampling", category: "Drilling" },
  { name: "Blast Hole Drilling Rig", spec: "40m max depth — DTH Method for mining", category: "Drilling" },
  { name: "Mud Rotary Rig", spec: "350m max — For loose formation clay and sandy soil", category: "Drilling" },
  { name: "Submersible Pump", spec: '6" diameter — 100,000 L/hr capacity for pumping tests', category: "Pumping" },
  { name: "Mobile Diesel Water Pump", spec: "Centrifugal dewatering pump — Diesel powered", category: "Dewatering" },
  { name: "DynaWater Pump", spec: "High-capacity dewatering system", category: "Dewatering" },
  { name: "Borehole Submersible Dewatering Pump", spec: "Deep well dewatering for mining pits", category: "Dewatering" },
  { name: "Monoblock Dewatering Pump", spec: "Compact dewatering for temporary works", category: "Dewatering" },
  { name: "Excavator", spec: "Heavy earthworks and trenching", category: "Civil" },
  { name: "Motor Grader", spec: "Road leveling and grading", category: "Civil" },
  { name: "Steel Drum Roller", spec: "Soil and asphalt compaction", category: "Civil" },
  { name: "Concrete Mixer", spec: "On-site concrete batching", category: "Civil" },
  { name: "Backhoe Loader", spec: "Versatile earthworks and loading", category: "Civil" },
  { name: "ABEM Terrameter SAS 1000", spec: "Resistivity measurement for hydrogeological survey", category: "Survey" },
  { name: "PQWT S-300", spec: "Natural electric field ERT survey — Electrical Resistivity Tomography", category: "Survey" },
];

export const TEAM = [
  { title: "Civil Engineers", qty: 3, type: "Permanent" },
  { title: "Geology Engineer", qty: 1, type: "Permanent" },
  { title: "GIS Expert / Land Surveyor", qty: 1, type: "Permanent" },
  { title: "Drilling Experts", qty: 5, type: "Permanent" },
  { title: "Mining Technician", qty: 1, type: "Permanent" },
  { title: "HSE Officers", qty: 2, type: "Permanent" },
  { title: "Drillers", qty: 5, type: "Permanent" },
];

export const TESTIMONIALS = [
  {
    name: "RUWASA Mtwara",
    role: "Regional Water Authority",
    content: "SEBA delivered the Chekeleni Village water extension project on time with exceptional quality. Their safety standards throughout the project were commendable.",
    rating: 5,
  },
  {
    name: "Gairo District Council",
    role: "Local Government Authority",
    content: "The piped water system constructed by SEBA has transformed water access for Ihenje Village. Professional team, modern equipment, and strict adherence to safety protocols.",
    rating: 5,
  },
  {
    name: "Stamigold Biharamulo",
    role: "Mining Company",
    content: "SEBA's monitoring borehole drilling services met all our technical requirements. Their expertise in dewatering and groundwater management is outstanding.",
    rating: 5,
  },
];

export const CLIENTS = [
  "RUWASA",
  "Njombe District Council",
  "Gairo District Council",
  "Stamigold",
  "Noravia Gold",
  "Nyanzaga Mining",
  "Katavi District Council",
  "Mtwara District Council",
  "Mpanda District Council",
  "Kilosa District Council",
  "Tandahimba District Council",
  "Simbo District Council",
];

export const CLIENT_LOGOS = [
  { name: "RUWASA", src: "/images/logos/Ruwasa logo.png" },
  { name: "Gairo District Council", src: "/images/logos/Gairo DC.png" },
  { name: "Katavi District Council", src: "/images/logos/KATAVI.png" },
  { name: "Mtwara District Council", src: "/images/logos/MTWARA LOGO.png" },
  { name: "Nyanzaga Mining", src: "/images/logos/NYANZAGA.webp" },
  { name: "Stamigold", src: "/images/logos/STAMIGOLD.png" },
  { name: "Njombe District Council", src: "/images/logos/njombe dc.png" },
];

export const BLOG_POSTS = [
  {
    title: "The Future of Groundwater Exploration in Tanzania",
    excerpt: "Advanced ERT technology is revolutionizing how we identify water sources, reducing exploration costs by up to 40% while improving accuracy.",
    date: "March 15, 2026",
    readTime: "5 min read",
    category: "Technology",
    image: "/images/Ground Water Exploration.jpg",
  },
  {
    title: "Why Safety Culture Matters in Drilling Operations",
    excerpt: "At SEBA, safety isn't just a policy—it's our foundation. Learn how our zero-incident record is maintained across all project sites.",
    date: "February 28, 2026",
    readTime: "4 min read",
    category: "Safety",
    image: "/images/Drilling Works.png",
  },
  {
    title: "Sustainable Irrigation Solutions for Tanzanian Agriculture",
    excerpt: "Modern irrigation schemes are transforming crop yields. Our latest projects demonstrate how engineered water systems boost agricultural productivity year-round.",
    date: "January 20, 2026",
    readTime: "6 min read",
    category: "Agriculture",
    image: "/images/Irrigation.jpg",
  },
];

export const SAFETY_POLICY = [
  "Safety is the most important attribute to all our activities.",
  "We ensure the health, safety, security and work environment of all members including visitors.",
  "We conduct environmental assessments and mitigate all impacts during and post-construction.",
  "We adapt all practical measures to protect and maintain the environment.",
  "We comply with all safety and environmental regulations.",
];
